name: Lint check, format check, and build

on:
  push:
    branches:
      - main
    paths: # We only run the workflow if the code in these files/directories changes
      - ".github/workflows/lint-format-test.yml" # This file
      - "src/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "src/**"

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: ./src

permissions:
  contents: read

jobs:
  lint-format-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install --no-save

      - name: Format check and lint
        run: |
          npm run format-check
          npm run lint
          continue-on-error: true
      - name: Build
        run: |
          npm run build
      - name: Unit Tets
        run: |
          npm run test
